package pia.database;
// Generated May 31, 2019 8:26:26 PM by Hibernate Tools 4.3.1



/**
 * AsocijacijaGrupa generated by hbm2java
 */
public class AsocijacijaGrupa  implements java.io.Serializable {


     private Integer idGrupa;
     private String rec1;
     private String rec2;
     private String rec3;
     private String rec4;
     private String resenjeGrupe;

    public AsocijacijaGrupa() {
    }

    public AsocijacijaGrupa(String rec1, String rec2, String rec3, String rec4, String resenjeGrupe) {
       this.rec1 = rec1;
       this.rec2 = rec2;
       this.rec3 = rec3;
       this.rec4 = rec4;
       this.resenjeGrupe = resenjeGrupe;
    }
   
    public Integer getIdGrupa() {
        return this.idGrupa;
    }
    
    public void setIdGrupa(Integer idGrupa) {
        this.idGrupa = idGrupa;
    }
    public String getRec1() {
        return this.rec1;
    }
    
    public void setRec1(String rec1) {
        this.rec1 = rec1;
    }
    public String getRec2() {
        return this.rec2;
    }
    
    public void setRec2(String rec2) {
        this.rec2 = rec2;
    }
    public String getRec3() {
        return this.rec3;
    }
    
    public void setRec3(String rec3) {
        this.rec3 = rec3;
    }
    public String getRec4() {
        return this.rec4;
    }
    
    public void setRec4(String rec4) {
        this.rec4 = rec4;
    }
    public String getResenjeGrupe() {
        return this.resenjeGrupe;
    }
    
    public void setResenjeGrupe(String resenjeGrupe) {
        this.resenjeGrupe = resenjeGrupe;
    }




}


