package pia.database;
// Generated May 31, 2019 8:26:26 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * IgraDana generated by hbm2java
 */
public class IgraDana implements java.io.Serializable
{

    private int idIgraDana;
    private String slagalica;
    private String mojBroj;
    private int skocko;
    private int idSpojnica;
    private int idAsocijacija;
    private Date datum;

    public IgraDana()
    {
    }

    public IgraDana(int idIgraDana, String slagalica, String mojBroj, int skocko, int idSpojnica, int idAsocijacija)
    {
        this.idIgraDana = idIgraDana;
        this.slagalica = slagalica;
        this.mojBroj = mojBroj;
        this.skocko = skocko;
        this.idSpojnica = idSpojnica;
        this.idAsocijacija = idAsocijacija;
    }

    public int getIdIgraDana()
    {
        return this.idIgraDana;
    }

    public void setIdIgraDana(int idIgraDana)
    {
        this.idIgraDana = idIgraDana;
    }

    public String getSlagalica()
    {
        return this.slagalica;
    }

    public void setSlagalica(String slagalica)
    {
        this.slagalica = slagalica;
    }

    public String getMojBroj()
    {
        return this.mojBroj;
    }

    public void setMojBroj(String mojBroj)
    {
        this.mojBroj = mojBroj;
    }

    public int getSkocko()
    {
        return this.skocko;
    }

    public void setSkocko(int skocko)
    {
        this.skocko = skocko;
    }

    public int getIdSpojnica()
    {
        return this.idSpojnica;
    }

    public void setIdSpojnica(int idSpojnica)
    {
        this.idSpojnica = idSpojnica;
    }

    public int getIdAsocijacija()
    {
        return this.idAsocijacija;
    }

    public void setIdAsocijacija(int idAsocijacija)
    {
        this.idAsocijacija = idAsocijacija;
    }

    public Date getDatum()
    {
        return this.datum;
    }

    public void setDatum(Date datum)
    {
        this.datum = datum;
    }

}
