package pia.database;
// Generated May 31, 2019 8:26:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Partija generated by hbm2java
 */
public class Partija  implements java.io.Serializable {


     private Integer idPartija;
     private Integer plaviTakmicar;
     private Integer crveniTakmicar;
     private byte samostalno;
     private Date datum;

    public Partija() {
    }

	
    public Partija(byte samostalno) {
        this.samostalno = samostalno;
    }
    public Partija(Integer plaviTakmicar, Integer crveniTakmicar, byte samostalno, Date datum) {
       this.plaviTakmicar = plaviTakmicar;
       this.crveniTakmicar = crveniTakmicar;
       this.samostalno = samostalno;
       this.datum = datum;
    }
   
    public Integer getIdPartija() {
        return this.idPartija;
    }
    
    public void setIdPartija(Integer idPartija) {
        this.idPartija = idPartija;
    }
    public Integer getPlaviTakmicar() {
        return this.plaviTakmicar;
    }
    
    public void setPlaviTakmicar(Integer plaviTakmicar) {
        this.plaviTakmicar = plaviTakmicar;
    }
    public Integer getCrveniTakmicar() {
        return this.crveniTakmicar;
    }
    
    public void setCrveniTakmicar(Integer crveniTakmicar) {
        this.crveniTakmicar = crveniTakmicar;
    }
    public byte getSamostalno() {
        return this.samostalno;
    }
    
    public void setSamostalno(byte samostalno) {
        this.samostalno = samostalno;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


