package pia.database;
// Generated May 31, 2019 8:26:26 PM by Hibernate Tools 4.3.1



/**
 * Rezultat generated by hbm2java
 */
public class Rezultat  implements java.io.Serializable {


     private int idRezultat;
     private int idPartija;
     private int igra;
     private int poenaPlavi;
     private int poenaCrveni;

    public Rezultat() {
    }

    public Rezultat(int idRezultat, int idPartija, int igra, int poenaPlavi, int poenaCrveni) {
       this.idRezultat = idRezultat;
       this.idPartija = idPartija;
       this.igra = igra;
       this.poenaPlavi = poenaPlavi;
       this.poenaCrveni = poenaCrveni;
    }
   
    public int getIdRezultat() {
        return this.idRezultat;
    }
    
    public void setIdRezultat(int idRezultat) {
        this.idRezultat = idRezultat;
    }
    public int getIdPartija() {
        return this.idPartija;
    }
    
    public void setIdPartija(int idPartija) {
        this.idPartija = idPartija;
    }
    public int getIgra() {
        return this.igra;
    }
    
    public void setIgra(int igra) {
        this.igra = igra;
    }
    public int getPoenaPlavi() {
        return this.poenaPlavi;
    }
    
    public void setPoenaPlavi(int poenaPlavi) {
        this.poenaPlavi = poenaPlavi;
    }
    public int getPoenaCrveni() {
        return this.poenaCrveni;
    }
    
    public void setPoenaCrveni(int poenaCrveni) {
        this.poenaCrveni = poenaCrveni;
    }




}


