package pia.database;
// Generated May 31, 2019 8:26:26 PM by Hibernate Tools 4.3.1



/**
 * Slagalica generated by hbm2java
 */
public class Slagalica  implements java.io.Serializable {


     private Integer idRecSlagalica;
     private String rec;

    public Slagalica() {
    }

    public Slagalica(String rec) {
       this.rec = rec;
    }
   
    public Integer getIdRecSlagalica() {
        return this.idRecSlagalica;
    }
    
    public void setIdRecSlagalica(Integer idRecSlagalica) {
        this.idRecSlagalica = idRecSlagalica;
    }
    public String getRec() {
        return this.rec;
    }
    
    public void setRec(String rec) {
        this.rec = rec;
    }




}


