package pia.database;
// Generated May 31, 2019 8:26:26 PM by Hibernate Tools 4.3.1



/**
 * SpojniceRec generated by hbm2java
 */
public class SpojniceRec  implements java.io.Serializable {


     private Integer id;
     private int idSpojnica;
     private String levaRec;
     private String desnaRec;

    public SpojniceRec() {
    }
    
    public SpojniceRec(String a, String levaRec, String desnaRec)
    {
       this.levaRec = levaRec;
       this.desnaRec = desnaRec;
    }

    public SpojniceRec(int idSpojnica, String levaRec, String desnaRec) {
       this.idSpojnica = idSpojnica;
       this.levaRec = levaRec;
       this.desnaRec = desnaRec;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdSpojnica() {
        return this.idSpojnica;
    }
    
    public void setIdSpojnica(int idSpojnica) {
        this.idSpojnica = idSpojnica;
    }
    public String getLevaRec() {
        return this.levaRec;
    }
    
    public void setLevaRec(String levaRec) {
        this.levaRec = levaRec;
    }
    public String getDesnaRec() {
        return this.desnaRec;
    }
    
    public void setDesnaRec(String desnaRec) {
        this.desnaRec = desnaRec;
    }




}


