package pia.database;
// Generated May 31, 2019 8:26:26 PM by Hibernate Tools 4.3.1



/**
 * Spojnice generated by hbm2java
 */
public class Spojnice  implements java.io.Serializable {


     private Integer idSpojnica;

    public Spojnice() {
    }
       
    public Integer getIdSpojnica() {
        return this.idSpojnica;
    }
    
    public void setIdSpojnica(Integer idSpojnica) {
        this.idSpojnica = idSpojnica;
    }




}


